### ISSUE TITLE
Resources Page

### ISSUE THREAD

**Issue by aworld1** [TritonSE/CBL-Mobile-Application#36]
~~***THIS ISSUE HAS A BLOCKER: THE CLIENT NEEDS TO SPECIFY THE RESOURCES PAGE***~~ EDIT: Designs are ready!

In this issue, the static resources page will do the following

- [ ] Each box will take the user to a specified hyperlink
- [ ] A link to the affirmation page
- [ ] Search bar that shows the resources with metadata matching the search query
- [ ] Delete the "Coming Soon" resource page 

[Figma Link](https://www.figma.com/file/j5xygYtD7uunBcSwXJp8kd/MVP-File?node-id=1923%3A31548&mode=dev)

**Comment by petabite** [comment]
Looks like this was started already: https://github.com/TritonSE/CBL-Mobile-Application/blob/main/lib/pages/resources.dart. Maybe we can use this as a starting point.
